import json

flight_routes = {"Aberdeen": {
        "Belfast": ["Air UK", "FlyBe"],
        "Birmingham": ["Loganair", "FlyBe"],
        "Bristol": ["Eastern Airways"],
        "Cardiff": ["Eastern Airways"],
        "Edinburgh": ["British Airways"],
        "Glasgow": ["FlyBe"],
        "London": ["British Airways", "Loganair"],
        "Manchester": ["FlyBe"]},
    "Belfast": {
        "Aberdeen": ["Air UK", "FlyBe"],
        "Birmingham": ["EasyJet", "FlyBe"],
        "Bristol": ["EasyJet"],
        "Cardiff": ["Eastern Airways"],
        "Edinburgh": ["EasyJet"],
        "Glasgow": ["British Airways"],
        "Liverpool": ["FlyBe"],
        "London": ["British Airways", "EasyJet"],
        "Manchester": ["EasyJet", "FlyBe"],
        "Newcastle upon Tyne": ["FlyBe"]},
    "Birmingham": {
        "Aberdeen": ["Loganair", "FlyBe"],
        "Belfast": ["EasyJet", "FlyBe"],
        "Edinburgh": ["Loganair", "British Airways"],
        "Glasgow": ["EasyJet", "FlyBe"],
        "London": ["British Airways"],
        "Manchester": ["FlyBe"],
        "Newcastle upon Tyne": ["EasyJet"]},
    "Bristol": {
        "Aberdeen": ["Eastern Airways"],
        "Belfast": ["EasyJet"],
        "Edinburgh": ["EasyJet"],
        "Glasgow": ["FlyBe"],
        "London": ["British Airways"],
        "Manchester": ["EasyJet"]},
    "Cardiff": {
        "Aberdeen": ["Eastern Airways"],
        "Belfast": ["Eastern Airways"],
        "Edinburgh": ["British Airways"],
        "Glasgow": ["FlyBe"],
        "London": ["British Airways"],
        "Manchester": ["EasyJet"]},
    "Edinburgh": {
        "Aberdeen": ["British Airways"],
        "Belfast": ["EasyJet"],
        "Birmingham": ["Loganair", "British Airways"],
        "Bristol": ["EasyJet"],
        "Cardiff": ["British Airways"],
        "Glasgow": ["FlyBe"],
        "London": ["British Airways", "Loganair"],
        "Manchester": ["FlyBe"],
        "Newcastle upon Tyne": ["EasyJet"]},
    "Glasgow": {
        "Aberdeen": ["FlyBe"],
        "Belfast": ["British Airways"],
        "Birmingham": ["EasyJet", "FlyBe"],
        "Bristol": ["FlyBe"],
        "Cardiff": ["FlyBe"],
        "Edinburgh": ["FlyBe"],
        "London": ["British Airways"],
        "Manchester": ["EasyJet"]},
    "Leeds": {
        "Belfast": ["FlyBe"],
        "London": ["British Airways"]},
    "Liverpool": {
        "Belfast": ["FlyBe"],
        "London": ["British Airways"]},
    "London": {
        "Aberdeen": ["British Airways", "Loganair"],
        "Belfast": ["British Airways", "EasyJet"],
        "Birmingham": ["British Airways"],
        "Bristol": ["British Airways"],
        "Cardiff": ["British Airways"],
        "Edinburgh": ["British Airways", "Loganair"],
        "Glasgow": ["British Airways"],
        "Leeds": ["British Airways"],
        "Liverpool": ["British Airways"],
        "Manchester": ["FlyBe", "British Airways"],
        "Newcastle upon Tyne": ["FlyBe"]},
    "Manchester": {
        "Aberdeen": ["FlyBe"],
        "Belfast": ["EasyJet", "FlyBe"],
        "Birmingham": ["FlyBe"],
        "Bristol": ["EasyJet"],
        "Cardiff": ["EasyJet"],
        "Edinburgh": ["FlyBe"],
        "Glasgow": ["EasyJet"],
        "London": ["FlyBe", "British Airways"],
        "Newcastle upon Tyne": ["EasyJet"]},
    "Newcastle upon Tyne": {
        "Belfast": ["FlyBe"],
        "Birmingham": ["EasyJet"],
        "Edinburgh": ["EasyJet"],
        "London": ["FlyBe"],
        "Manchester": ["EasyJet"]}}

train_routes = {"London": {
        "Manchester": ["Avanti West Coast", "CrossCountry"],
        "Birmingham": ["Avanti West Coast", "London Northwestern Railway"],
        "Edinburgh": ["LNER", "Avanti West Coast"],
        "Leeds": ["LNER", "Northern Trains"],
        "Bristol": ["Great Western Railway "],
        "Cardiff": ["Great Western Railway "],
        "Glasgow": ["Avanti West Coast", "LNER"],
        "Liverpool": ["Avanti West Coast", "London Northwestern Railway"],
        "Newcastle upon Tyne": ["LNER"],
    },
    "Manchester": {
        "London": ["Avanti West Coast", "CrossCountry"],
        "Edinburgh": ["TransPennine Express"],
        "Leeds": ["TransPennine Express", "Northern Trains"],
        "Birmingham": ["CrossCountry"],
        "Liverpool": ["Northern Trains", "TransPennine Express"],
        "Newcastle upon Tyne": ["CrossCountry"],
        "Glasgow": ["TransPennine Express"],
    },
    "Edinburgh": {
        "London": ["LNER", "Avanti West Coast"],
        "Manchester": ["TransPennine Express"],
        "Newcastle upon Tyne": ["LNER", "CrossCountry"],
        "Glasgow": ["ScotRail"],
        "Birmingham": ["CrossCountry"],
    },
    "Birmingham": {
        "London": ["Avanti West Coast", "London Northwestern Railway"],
        "Manchester": ["CrossCountry"],
        "Glasgow": ["Avanti West Coast"],
        "Edinburgh": ["CrossCountry"],
        "Cardiff": ["CrossCountry"],
        "Bristol": ["CrossCountry"],
        "Leeds": ["CrossCountry"],
    },
    "Leeds": {
        "London": ["LNER", "Northern Trains"],
        "Manchester": ["TransPennine Express", "Northern Trains"],
        "Edinburgh": ["LNER"],
        "Birmingham": ["CrossCountry"],
        "Newcastle upon Tyne": ["LNER"],
    },
    "Bristol": {
        "London": ["Great Western Railway "],
        "Cardiff": ["Great Western Railway "],
        "Birmingham": ["CrossCountry"],
        "Manchester": ["CrossCountry"],
        "Leeds": ["CrossCountry"],
    },
    "Cardiff": {
        "London": ["Great Western Railway "],
        "Bristol": ["Great Western Railway "],
        "Birmingham": ["CrossCountry"],
        "Manchester": ["CrossCountry"],
    },
    "Glasgow": {
        "London": ["Avanti West Coast", "LNER"],
        "Manchester": ["TransPennine Express"],
        "Edinburgh": ["ScotRail"],
        "Birmingham": ["Avanti West Coast"],
        "Newcastle upon Tyne": ["LNER"],
    },
    "Newcastle upon Tyne": {
        "London": ["LNER"],
        "Manchester": ["CrossCountry"],
        "Edinburgh": ["LNER", "CrossCountry"],
        "Glasgow": ["LNER"],
        "Leeds": ["LNER"],
    },
    "Liverpool": {
        "London": ["Avanti West Coast"],
        "Manchester": ["Northern Trains", "TransPennine Express"],
        "Birmingham": ["London Northwestern Railway"],
    }
}

coach_routes = {
    "London": {
        "Manchester": ["National Express", "Megabus"],
        "Birmingham": ["National Express", "FlixBus"],
        "Edinburgh": ["National Express", "Megabus"],
        "Leeds": ["Megabus", "FlixBus"],
        "Bristol": ["National Express", "FlixBus"],
        "Cardiff": ["National Express", "Megabus"],
        "Glasgow": ["National Express"],
        "Liverpool": ["National Express", "Megabus"],
        "Newcastle upon Tyne": ["Megabus", "National Express"],
    },
    "Manchester": {
        "London": ["National Express", "Megabus"],
        "Edinburgh": ["Megabus"],
        "Leeds": ["National Express", "Megabus"],
        "Birmingham": ["FlixBus", "National Express"],
        "Liverpool": ["National Express"],
        "Newcastle upon Tyne": ["Megabus"],
        "Glasgow": ["National Express"],
    },
    "Edinburgh": {
        "London": ["National Express", "Megabus"],
        "Manchester": ["Megabus"],
        "Newcastle upon Tyne": ["National Express"],
        "Glasgow": ["Megabus", "National Express"],
        "Birmingham": ["National Express"],
    },
    "Birmingham": {
        "London": ["National Express", "FlixBus"],
        "Manchester": ["FlixBus", "National Express"],
        "Glasgow": ["National Express"],
        "Edinburgh": ["National Express"],
        "Cardiff": ["National Express"],
        "Bristol": ["FlixBus"],
        "Leeds": ["Megabus"],
    },
    "Leeds": {
        "London": ["Megabus", "FlixBus"],
        "Manchester": ["National Express", "Megabus"],
        "Edinburgh": ["National Express"],
        "Birmingham": ["Megabus"],
        "Newcastle upon Tyne": ["National Express"],
    },
    "Bristol": {
        "London": ["National Express", "FlixBus"],
        "Cardiff": ["National Express"],
        "Birmingham": ["FlixBus"],
        "Manchester": ["National Express"],
    },
    "Cardiff": {
        "London": ["National Express", "Megabus"],
        "Bristol": ["National Express"],
        "Birmingham": ["National Express"],
        "Manchester": ["National Express"],
    },
    "Glasgow": {
        "London": ["National Express"],
        "Manchester": ["National Express"],
        "Edinburgh": ["Megabus", "National Express"],
        "Birmingham": ["National Express"],
        "Newcastle upon Tyne": ["National Express"],
    },
    "Newcastle upon Tyne": {
        "London": ["Megabus", "National Express"],
        "Manchester": ["Megabus"],
        "Edinburgh": ["National Express"],
        "Glasgow": ["National Express"],
        "Leeds": ["National Express"],
    },
    "Liverpool": {
        "London": ["National Express", "Megabus"],
        "Manchester": ["National Express"],
        "Birmingham": ["National Express"],
    },
}

airport_names = {
    "Aberdeen": "Aberdeen International Airport ",
    "Belfast": "Belfast International Airport ",
    "Birmingham": "Birmingham Airport ",
    "Bristol": "Bristol Airport ",
    "Cardiff": "Cardiff Airport ",
    "Edinburgh": "Edinburgh Airport ",
    "Glasgow": "Glasgow Airport ",
    "Leeds": "Leeds Bradford Airport ",
    "Liverpool": "Liverpool John Lennon Airport ",
    "London": "London Heathrow Airport ",
    "Manchester": "Manchester Airport ",
    "Newcastle upon Tyne": "Newcastle International Airport "
}

train_stations = {
    "London": "London King's Cross Station",
    "Manchester": "Manchester Piccadilly Station",
    "Birmingham": "Birmingham New Street Station",
    "Edinburgh": "Edinburgh Waverley Station",
    "Leeds": "Leeds Railway Station",
    "Bristol": "Bristol Temple Meads Station",
    "Cardiff": "Cardiff Central Station",
    "Glasgow": "Glasgow Central Station",
    "Newcastle upon Tyne": "Newcastle Central Station",
    "Liverpool": "Liverpool Lime Street Station",
    "Aberdeen": "Aberdeen Railway Station",
    "Belfast": "Belfast Lanyon Place Station",
    "Bath": "Bath Spa Station",
    "Brighton and Hove": "Brighton Railway Station",
    "Cambridge": "Cambridge Railway Station",
    "Coventry": "Coventry Railway Station",
    "Derby": "Derby Railway Station",
    "Derry": "Londonderry Railway Station",
    "Dundee": "Dundee Railway Station",
    "Exeter": "Exeter St Davids Station",
    "Inverness": "Inverness Railway Station",
    "Leicester": "Leicester Railway Station",
    "Norwich": "Norwich Railway Station",
    "Nottingham": "Nottingham Railway Station",
    "Oxford": "Oxford Railway Station",
    "Peterborough": "Peterborough Railway Station",
    "Plymouth": "Plymouth Railway Station",
    "Portsmouth": "Portsmouth & Southsea Station",
    "Sheffield": "Sheffield Railway Station",
    "Southampton": "Southampton Central Station",
    "Stoke-on-Trent": "Stoke-on-Trent Railway Station",
    "Sunderland": "Sunderland Railway Station",
    "Wolverhampton": "Wolverhampton Railway Station",
    "York": "York Railway Station"
}

coach_stops = {
    "London": "Victoria Coach Station",
    "Manchester": "Manchester Chorlton Street Coach Station",
    "Birmingham": "Birmingham Coach Station (Digbeth)",
    "Edinburgh": "Edinburgh Bus Station",
    "Leeds": "Leeds Coach Station",
    "Bristol": "Bristol Bus and Coach Station",
    "Cardiff": "Cardiff Coach Station",
    "Glasgow": "Buchanan Bus Station",
    "Newcastle upon Tyne": "Newcastle Coach Station",
    "Liverpool": "Liverpool One Bus Station",
    "Aberdeen": "Aberdeen Bus Station",
    "Belfast": "Belfast Europa Bus Centre",
    "Brighton and Hove": "Pool Valley Coach Station",
    "Bath": "Bath Bus Station",
    "Cambridge": "Cambridge Parkside Coach Stop",
    "Coventry": "Coventry Pool Meadow Bus Station",
    "Derby": "Derby Bus Station",
    "Derry": "Foyle Street Bus Station",
    "Dundee": "Dundee Seagate Bus Station",
    "Exeter": "Exeter Bus Station",
    "Inverness": "Inverness Bus Station",
    "Leicester": "Leicester St Margaret's Bus Station",
    "Norwich": "Norwich Bus Station",
    "Nottingham": "Nottingham Broadmarsh Bus Station",
    "Oxford": "Oxford Gloucester Green Bus Station",
    "Peterborough": "Peterborough Queensgate Bus Station",
    "Plymouth": "Plymouth Coach Station",
    "Portsmouth": "Portsmouth Coach Station",
    "Sheffield": "Sheffield Interchange",
    "Southampton": "Southampton Coach Station",
    "Stoke-on-Trent": "Stoke-on-Trent Bus Station",
    "Sunderland": "Park Lane Interchange",
    "Wolverhampton": "Wolverhampton Bus Station",
    "York": "York Station Coach Stop",
}

cities_in_uk = ["Aberdeen", "Bath", "Belfast", "Birmingham", "Brighton and Hove", 
    "Bristol", "Cambridge", "Cardiff", "Coventry", "Derby", "Derry", 
    "Dundee", "Edinburgh", "Exeter", "Glasgow", "Inverness", "Leeds", 
    "Leicester", "Liverpool", "London", "Manchester", "Newcastle upon Tyne", 
    "Norwich", "Nottingham", "Oxford", "Peterborough", "Plymouth", 
    "Portsmouth", "Sheffield", "Southampton", "Stoke-on-Trent", 
    "Sunderland", "Wolverhampton", "York"]

data = {"flight_routes": flight_routes,
        "train_routes": train_routes,
        "coach_routes": coach_routes,
        "airport_names": airport_names,
        "train_stations": train_stations,
        "coach_stops": coach_stops,
        "cities_in_uk": cities_in_uk}

file_name = "data.json"
with open(file_name, "w") as file:
    json.dump(data, file, indent=4)
        
print(f"JSON file '{file_name}' has been created.")